version: "2"
checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 250
  method-complexity:
    enabled: true
    config:
      threshold: 5
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 25
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: false
  similar-code:
    enabled: true
    config:
      threshold: 28
  identical-code:
    enabled: true
    config:
      threshold: 28
plugins:
 eslint:
  enabled: true
exclude_patterns:
- "bootstrap/"
- "config/"
- "database/"
- "features/"
- "**/node_modules/"
- "public/daterangepicker/"
- "**/spec/"
- "storage/"
- "tests/"
